import Face from '@assets/imgs/Face.png';

export const UserData = [
	{
		id: '1',
		profile: Face,
		name: 'wahab',
		email: 'wahab@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '2',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '3',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '4',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '5',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '6',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '7',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},

	{
		id: '8',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '9',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '10',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '11',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '12',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '13',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
	{
		id: '14',
		profile: Face,
		name: 'Abid ali',
		email: 'abidali@gmail.com',
		product: '32',
		totalSell: '2164',
		status: 'Active',
		joinOn: '2020-01-02',
	},
];
